-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.account_deletion_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  broker_id uuid,
  email text,
  phone text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  deletion_type text NOT NULL DEFAULT 'soft'::text CHECK (deletion_type = ANY (ARRAY['soft'::text, 'hard'::text])),
  reason text,
  requested_ip text,
  requested_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  processed_at timestamp with time zone,
  processed_by_admin_id uuid,
  CONSTRAINT account_deletion_requests_pkey PRIMARY KEY (id),
  CONSTRAINT account_deletion_requests_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES public.brokers(id),
  CONSTRAINT account_deletion_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.ad_campaign_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  broker_id uuid NOT NULL UNIQUE,
  gender USER-DEFINED NOT NULL DEFAULT 'all'::campaign_gender CHECK (gender = ANY (ARRAY['all'::text, 'male'::text, 'female'::text])),
  area_details jsonb DEFAULT '[]'::jsonb,
  targeting_suggestions jsonb DEFAULT '[]'::jsonb,
  start_age_range integer NOT NULL DEFAULT 18 CHECK (start_age_range >= 13 AND start_age_range <= 100),
  end_age_range integer NOT NULL DEFAULT 65,
  campaign_start_time text,
  campaign_end_time text,
  campaign_is_all_day boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ad_campaign_settings_pkey PRIMARY KEY (id),
  CONSTRAINT ad_campaign_settings_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES public.brokers(id)
);
CREATE TABLE public.addresses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  full_address text NOT NULL,
  latitude double precision,
  longitude double precision,
  city text,
  pincode text,
  state text,
  country text,
  landmark text,
  entity_type text NOT NULL,
  entity_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  search_text text,
  fts tsvector,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  unit_number text,
  building_name text,
  CONSTRAINT addresses_pkey PRIMARY KEY (id)
);
CREATE TABLE public.attachments (
  id bigint NOT NULL DEFAULT nextval('attachments_id_seq'::regclass),
  entity_type text NOT NULL,
  entity_id text NOT NULL,
  url text NOT NULL,
  r2_key text,
  file_name text,
  file_type text,
  file_size bigint,
  is_cover boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  CONSTRAINT attachments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.brokers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_name text NOT NULL,
  onboarding_status text NOT NULL DEFAULT 'pending'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  is_active boolean NOT NULL DEFAULT true,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  address_id uuid,
  search_text text,
  fts tsvector,
  auto_approve_video_requests boolean NOT NULL DEFAULT false,
  setup_details jsonb DEFAULT '{"account_created": true, "facebook_connected": false, "business_info_added": false, "instagram_connected": false, "properties_imported": false}'::jsonb,
  broker_code text NOT NULL UNIQUE CHECK (broker_code = upper(broker_code)),
  marketing_team_id uuid,
  primary_marketing_user_id uuid,
  user_id uuid,
  CONSTRAINT brokers_pkey PRIMARY KEY (id),
  CONSTRAINT brokers_address_id_fkey FOREIGN KEY (address_id) REFERENCES public.addresses(id),
  CONSTRAINT brokers_marketing_team_id_fkey FOREIGN KEY (marketing_team_id) REFERENCES public.marketing_teams(id),
  CONSTRAINT brokers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.chat_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  room_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  sender_type character varying NOT NULL DEFAULT 'broker'::character varying,
  message text,
  message_type USER-DEFINED NOT NULL DEFAULT 'text'::chat_message_type,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  medias jsonb DEFAULT '[]'::jsonb,
  is_edited boolean NOT NULL DEFAULT false,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  location_data jsonb DEFAULT '{}'::jsonb,
  reply_message_id uuid,
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_messages_reply_message_id_fkey FOREIGN KEY (reply_message_id) REFERENCES public.chat_messages(id),
  CONSTRAINT chat_messages_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.chat_rooms(id)
);
CREATE TABLE public.chat_rooms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  video_request_id uuid UNIQUE,
  broker_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  support_ticket_id uuid,
  room_type text NOT NULL DEFAULT 'video_request'::text CHECK (room_type = ANY (ARRAY['video_request'::text, 'support_ticket'::text])),
  CONSTRAINT chat_rooms_pkey PRIMARY KEY (id),
  CONSTRAINT chat_rooms_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES public.brokers(id),
  CONSTRAINT chat_rooms_video_request_id_fkey FOREIGN KEY (video_request_id) REFERENCES public.video_requests(id),
  CONSTRAINT chat_rooms_support_ticket_id_fkey FOREIGN KEY (support_ticket_id) REFERENCES public.support_tickets(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sender_id uuid,
  notification_type USER-DEFINED NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  receiver_ids ARRAY,
  video_request_id uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  image_url text,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.users(id),
  CONSTRAINT notifications_video_request_id_fkey FOREIGN KEY (video_request_id) REFERENCES public.video_requests(id)
);
CREATE TABLE public.properties (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  broker_id uuid NOT NULL,
  address_id uuid,
  property_title text NOT NULL,
  property_description text,
  property_type USER-DEFINED NOT NULL DEFAULT 'apartment'::property_type_enum,
  listing_type USER-DEFINED NOT NULL DEFAULT 'sale'::listing_type_enum,
  price numeric NOT NULL,
  area numeric NOT NULL,
  area_unit USER-DEFINED DEFAULT 'sqft'::area_unit_enum,
  bedrooms integer DEFAULT 0,
  bathrooms integer DEFAULT 0,
  balconies integer DEFAULT 0,
  parking integer DEFAULT 0,
  floor_number integer,
  total_floors integer,
  furnishing_status USER-DEFINED DEFAULT 'unfurnished'::furnishing_status_enum,
  property_status USER-DEFINED DEFAULT 'available'::property_status_enum,
  construction_status USER-DEFINED DEFAULT 'ready_to_move'::construction_status_enum,
  facing USER-DEFINED DEFAULT 'east'::facing_direction_enum,
  amenities jsonb DEFAULT '[]'::jsonb,
  medias jsonb DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  search_text text,
  fts tsvector,
  property_code text NOT NULL UNIQUE CHECK (property_code = upper(property_code)),
  rera_number text,
  CONSTRAINT properties_pkey PRIMARY KEY (id),
  CONSTRAINT properties_address_id_fkey FOREIGN KEY (address_id) REFERENCES public.addresses(id),
  CONSTRAINT properties_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES public.brokers(id)
);
CREATE TABLE public.social_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  broker_id uuid NOT NULL,
  platform USER-DEFINED NOT NULL,
  facebook_user_id text,
  page_id text,
  page_name text,
  page_access_token text,
  instagram_account_id text,
  instagram_username text,
  access_token text NOT NULL,
  expires_at timestamp with time zone,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_connected boolean DEFAULT true,
  search_text text,
  fts tsvector,
  ad_account_id text,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  CONSTRAINT social_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT social_accounts_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES public.brokers(id)
);
CREATE TABLE public.social_leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  user_name text NOT NULL,
  notes text,
  social_post_id uuid,
  search_text text,
  fts tsvector,
  phone text,
  phone_country_code text DEFAULT '91'::text,
  phone_country_iso text DEFAULT 'IN'::text,
  property_details text,
  broker_id uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  property_id uuid,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::lead_status_enum,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT social_leads_pkey PRIMARY KEY (id),
  CONSTRAINT social_leads_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES public.brokers(id),
  CONSTRAINT social_leads_social_post_id_fkey FOREIGN KEY (social_post_id) REFERENCES public.social_posts(id),
  CONSTRAINT social_leads_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id)
);
CREATE TABLE public.social_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  broker_id uuid NOT NULL,
  platform USER-DEFINED NOT NULL,
  page_id text NOT NULL,
  post_id text NOT NULL,
  caption text,
  media_urls jsonb DEFAULT '[]'::jsonb,
  permalink text,
  views_count integer DEFAULT 0,
  comment_count integer DEFAULT 0,
  likes_count integer DEFAULT 0,
  published_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  search_text text,
  fts tsvector,
  property_id uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  CONSTRAINT social_posts_pkey PRIMARY KEY (id),
  CONSTRAINT social_posts_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES public.brokers(id),
  CONSTRAINT social_posts_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id)
);
CREATE TABLE public.subscription_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  amount numeric NOT NULL DEFAULT 0.00,
  description text NOT NULL DEFAULT ''::text,
  benefits jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_popular boolean NOT NULL DEFAULT false,
  payment_provider USER-DEFINED DEFAULT 'razorpay'::payment_provider_type,
  billing_type USER-DEFINED NOT NULL,
  duration_options jsonb NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT subscription_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_otps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  email text,
  otp text NOT NULL,
  otp_type USER-DEFINED NOT NULL,
  expiry_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_otps_pkey PRIMARY KEY (id),
  CONSTRAINT user_otps_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  phone text,
  role USER-DEFINED NOT NULL DEFAULT 'broker'::user_role,
  is_active boolean NOT NULL DEFAULT true,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  broker_id uuid,
  phone_country_code text DEFAULT '91'::text,
  phone_country_iso text DEFAULT 'IN'::text,
  search_text text,
  fts tsvector,
  gender USER-DEFINED DEFAULT 'other'::user_gender,
  date_of_birth date,
  notes text,
  cover_image jsonb,
  inactive_reason text,
  delete_reason text,
  activated_at timestamp with time zone,
  inactivated_at timestamp with time zone,
  is_email_verified boolean DEFAULT false,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES public.brokers(id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.video_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  property_id uuid NOT NULL,
  broker_id uuid NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::video_request_status,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  notes text,
  admin_approval_status USER-DEFINED NOT NULL DEFAULT 'pending'::video_request_approval_status,
  completed_at timestamp with time zone,
  cancel_reason text,
  admin_cancel_reason text,
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  cancelled_by_user_id uuid,
  CONSTRAINT video_requests_pkey PRIMARY KEY (id),
  CONSTRAINT video_requests_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES public.brokers(id),
  CONSTRAINT video_requests_cancelled_by_user_id_fkey FOREIGN KEY (cancelled_by_user_id) REFERENCES public.users(id),
  CONSTRAINT video_requests_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id)
);
CREATE TABLE public.user_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  broker_id uuid NOT NULL,
  subscription_plan_id uuid,
  amount numeric NOT NULL,
  purpose USER-DEFINED NOT NULL DEFAULT 'buy_subscription'::payment_purpose_type,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::payment_status_type,
  payment_provider USER-DEFINED NOT NULL DEFAULT 'razorpay'::payment_provider_type,
  payment_id text,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_payments_pkey PRIMARY KEY (id),
  CONSTRAINT user_payments_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES public.brokers(id),
  CONSTRAINT user_payments_subscription_plan_id_fkey FOREIGN KEY (subscription_plan_id) REFERENCES public.subscription_plans(id)
);
CREATE TABLE public.user_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  broker_id uuid NOT NULL,
  payment_id uuid NOT NULL,
  subscription_plan_id uuid NOT NULL,
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone NOT NULL,
  total_days integer NOT NULL,
  amount numeric NOT NULL,
  plan_code text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT user_subscriptions_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES public.brokers(id),
  CONSTRAINT user_subscriptions_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.user_payments(id),
  CONSTRAINT user_subscriptions_plan_id_fkey FOREIGN KEY (subscription_plan_id) REFERENCES public.subscription_plans(id)
);
CREATE TABLE public.property_visits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  broker_id uuid NOT NULL,
  property_id uuid NOT NULL,
  client_name text NOT NULL,
  client_phone text NOT NULL,
  phone_country_code text DEFAULT '91'::text,
  phone_country_iso text DEFAULT 'IN'::text,
  visit_date date NOT NULL,
  time_slot text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'rescheduled'::text, 'completed'::text, 'cancelled'::text, 'no_show'::text])),
  notes text,
  reschedule_count integer NOT NULL DEFAULT 0,
  reschedule_reason text,
  cancelled_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  search_text text,
  fts tsvector,
  CONSTRAINT property_visits_pkey PRIMARY KEY (id),
  CONSTRAINT property_visits_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES public.brokers(id),
  CONSTRAINT property_visits_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id)
);
CREATE TABLE public.property_visit_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  visit_id uuid NOT NULL,
  action text NOT NULL,
  previous_status text,
  new_status text,
  previous_visit_date date,
  new_visit_date date,
  previous_time_slot text,
  new_time_slot text,
  reason text,
  notes text,
  changed_by_user_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT property_visit_history_pkey PRIMARY KEY (id),
  CONSTRAINT property_visit_history_visit_id_fkey FOREIGN KEY (visit_id) REFERENCES public.property_visits(id),
  CONSTRAINT property_visit_history_changed_by_user_id_fkey FOREIGN KEY (changed_by_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.property_faqs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  property_id uuid NOT NULL,
  question text NOT NULL,
  answer text NOT NULL,
  display_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT property_faqs_pkey PRIMARY KEY (id),
  CONSTRAINT property_faqs_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id)
);
CREATE TABLE public.support_tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ticket_number text NOT NULL,
  ticket_counter integer NOT NULL,
  broker_id uuid NOT NULL,
  user_id uuid NOT NULL,
  full_name text NOT NULL,
  email text NOT NULL,
  phone text,
  category text NOT NULL,
  subject text NOT NULL,
  description text NOT NULL,
  attachments jsonb DEFAULT '[]'::jsonb,
  status text NOT NULL DEFAULT 'open'::text,
  priority text NOT NULL DEFAULT 'normal'::text,
  admin_notes text,
  assigned_to uuid,
  reopen_requested boolean DEFAULT false,
  reopen_reason text,
  resolved_at timestamp with time zone,
  closed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  is_deleted boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  CONSTRAINT support_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT support_tickets_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES public.brokers(id),
  CONSTRAINT support_tickets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT support_tickets_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id)
);
CREATE TABLE public.chat_room_participants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  room_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL DEFAULT 'member'::text,
  last_read_message_id uuid,
  last_read_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  joined_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  is_muted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT chat_room_participants_pkey PRIMARY KEY (id),
  CONSTRAINT chat_room_participants_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.chat_rooms(id),
  CONSTRAINT chat_room_participants_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT chat_room_participants_last_read_message_id_fkey FOREIGN KEY (last_read_message_id) REFERENCES public.chat_messages(id)
);
CREATE TABLE public.user_devices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  device_id text NOT NULL,
  device_name text NOT NULL,
  platform USER-DEFINED NOT NULL DEFAULT 'android'::device_platform_enum,
  fcm_token text,
  app_version text,
  build_number integer,
  os_version text,
  ip_address text,
  user_agent text,
  is_active boolean NOT NULL DEFAULT true,
  last_active_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_devices_pkey PRIMARY KEY (id),
  CONSTRAINT user_devices_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.marketing_teams (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  territory text,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT marketing_teams_pkey PRIMARY KEY (id),
  CONSTRAINT marketing_teams_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.marketing_team_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  team_id uuid NOT NULL,
  user_id uuid NOT NULL,
  is_lead boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT marketing_team_members_pkey PRIMARY KEY (id),
  CONSTRAINT marketing_team_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT marketing_team_members_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.marketing_teams(id)
);
CREATE TABLE public.broker_assignment_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  broker_id uuid NOT NULL,
  previous_team_id uuid,
  new_team_id uuid,
  previous_user_id uuid,
  new_user_id uuid,
  changed_by uuid,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT broker_assignment_history_pkey PRIMARY KEY (id),
  CONSTRAINT broker_assignment_history_broker_id_fkey FOREIGN KEY (broker_id) REFERENCES public.brokers(id),
  CONSTRAINT broker_assignment_history_previous_team_id_fkey FOREIGN KEY (previous_team_id) REFERENCES public.marketing_teams(id),
  CONSTRAINT broker_assignment_history_new_team_id_fkey FOREIGN KEY (new_team_id) REFERENCES public.marketing_teams(id),
  CONSTRAINT broker_assignment_history_previous_user_id_fkey FOREIGN KEY (previous_user_id) REFERENCES public.users(id),
  CONSTRAINT broker_assignment_history_new_user_id_fkey FOREIGN KEY (new_user_id) REFERENCES public.users(id),
  CONSTRAINT broker_assignment_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.users(id)
);