// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCih1Kp59mpAoJw15Hp1IGN523I2vdo0HU',
    appId: '1:209800510781:web:d597da015be9ba994d1954',
    messagingSenderId: '209800510781',
    projectId: 'broker-agencies-flutter',
    authDomain: 'broker-agencies-flutter.firebaseapp.com',
    storageBucket: 'broker-agencies-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxplSV83y_AWx5K2wa8LiB6j3zUA-g2MI',
    appId: '1:209800510781:android:ec47db589c29274c4d1954',
    messagingSenderId: '209800510781',
    projectId: 'broker-agencies-flutter',
    storageBucket: 'broker-agencies-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_BtXGGx0QOEHLdCZDwIQAXWRiFRxAqyI',
    appId: '1:209800510781:ios:dc8bdbbf88ed6b924d1954',
    messagingSenderId: '209800510781',
    projectId: 'broker-agencies-flutter',
    storageBucket: 'broker-agencies-flutter.firebasestorage.app',
    iosBundleId: 'com.digipie.admin.brokerflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_BtXGGx0QOEHLdCZDwIQAXWRiFRxAqyI',
    appId: '1:209800510781:ios:cc652997f2884f8f4d1954',
    messagingSenderId: '209800510781',
    projectId: 'broker-agencies-flutter',
    storageBucket: 'broker-agencies-flutter.firebasestorage.app',
    iosBundleId: 'com.example.brokerflowAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCih1Kp59mpAoJw15Hp1IGN523I2vdo0HU',
    appId: '1:209800510781:web:85c0681dd7af1a934d1954',
    messagingSenderId: '209800510781',
    projectId: 'broker-agencies-flutter',
    authDomain: 'broker-agencies-flutter.firebaseapp.com',
    storageBucket: 'broker-agencies-flutter.firebasestorage.app',
  );
}
